version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: todo_app
    volumes:
      - db:/data/db

  web:
    build: .
    image: flask-app
    ports:
      - 5000:5000
    depends_on:
      - mongodb

volumes:
  db: