version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: todo_app
    volumes:
      - db:/data/db

  web:
    image: 'jpmontoya19/cisco_demo:flask-app'
    ports:
      - 80:5000
    depends_on:
      - mongodb

volumes:
  db: